### ISSUE TITLE
add community guidelines documents

### ISSUE THREAD

**Issue by benmarwick** [zoometh/iconr#73]
As part of the [JOSS review process](https://github.com/openjournals/joss-reviews/issues/3191#issuecomment-841344707), I have noticed that the project is lacking **Community guidelines.** We do not see "clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support"

I recommend to add 
- [x] a CONTRIBUTING.md document (e.g. https://github.com/tidyverse/tidyverse/blob/master/.github/CONTRIBUTING.md) and 
- [x] a CODE_OF_CONDUCT.md document (e.g. https://github.com/tidyverse/tidyverse/blob/master/.github/CODE_OF_CONDUCT.md) and 
- [x] Issue templates (e.g. https://github.com/tidyverse/tidyverse/tree/master/.github/ISSUE_TEMPLATE)

**Comment by zoometh** [comment]
@benmarwick I've added the missing guidelines documents:

- [CONTRIBUTING.md](https://github.com/zoometh/iconr/blob/master/.github/CONTRIBUTING.md) 
- [CODE_OF_CONDUCT.md](https://github.com/zoometh/iconr/blob/master/.github/CODE_OF_CONDUCT.md)
- [Issue templates](https://github.com/zoometh/iconr/blob/master/.github/ISSUE_TEMPLATE.md)
